# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BowlEffect
                                 A QGIS plugin
 This plugin removes bowl effect from a DOD
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-06-02
        copyright            : (C) 2023 by LETG, IUEM (Plouzané, France)
        email                : antoineledoeuff@yahoo.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'LETG, IUEM (Plouzané, France)'
__date__ = '2023-06-02'
__copyright__ = '(C) 2023 by LETG, IUEM (Plouzané, France)'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BowlEffect class from file BowlEffect.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rem_bowl_effect import BowlEffectPlugin
    return BowlEffectPlugin()
